from django.urls import path
from OTS.views import (
    api_practice_check, api_practice_questions, api_subject_question_bank, api_practice_submit,
    teacher_dashboard, teacherLoginView, teacherRegistrationForm, teacherRegistration,
    teacher_add_subject, teacher_add_test, teacher_add_question, teacher_students, teacher_results,
    teacher_delete_test,
    add_questions, add_subject, add_test, full_upload, toggle_test,
    api_questions, api_subjects, api_tests, api_leaderboard,
    api_all_students, api_test_results, update_duration,
    calculateTestResult, candidateHome, candidateRegistration,
    candidateRegistrationform, loginView, logOutView,
    studentPortal, teacherPortal,
    showTestResult, testPaper, testByToken, testResultHistory, welcome,
    practice_questions,
)

app_name = "OTS"

urlpatterns = [
    path("", welcome),
    path("student/", studentPortal, name="student_portal"),
    path("teacher/portal/", teacherPortal, name="teacher_portal"),
    path("new-candidate", candidateRegistrationform, name="RegistrationForm"),
    path("store-candidate", candidateRegistration,   name="store_candidate"),
    path("login",           loginView,               name="Loginform"),
    path("home",            candidateHome,           name="home"),
    path("test-paper",      testPaper,               name="testpaper"),
    path("test/<uuid:token>/", testByToken,          name="test_by_token"),
    path("calculate-result",calculateTestResult,     name="calculateTest"),
    path("test-history",    testResultHistory,       name="testHistory"),
    path("result",          showTestResult,          name="result"),
    path("logout",          logOutView,              name="Logout"),
    path("practice",        practice_questions,      name="practice"),
    path("teacher/",        teacher_dashboard,       name="teacher_dashboard"),
    path("teacher/add-subject/", teacher_add_subject, name="teacher_add_subject"),
    path("teacher/add-test/", teacher_add_test, name="teacher_add_test"),
    path("teacher/add-question/", teacher_add_question, name="teacher_add_question"),
    path("teacher/students/", teacher_students, name="teacher_students"),
    path("teacher/results/", teacher_results, name="teacher_results"),
    path("teacher/delete-test/<int:test_id>/", teacher_delete_test, name="teacher_delete_test"),
    path("teacher/login/",  teacherLoginView,        name="teacher_login"),
    path("teacher/register/", teacherRegistrationForm, name="teacher_register"),
    path("teacher/store/", teacherRegistration, name="teacher_store"),
    # Teacher APIs
    path("api/add-subject/",               add_subject),
    path("api/add-test/",                  add_test),
    path("api/add-questions/",             add_questions),
    path("api/full-upload/",               full_upload),
    path("api/toggle-test/<int:test_id>/", toggle_test,        name="toggle_test"),
    path("api/all-students/",              api_all_students,   name="api_all_students"),
    path("api/test-results/<int:test_id>/",api_test_results,   name="api_test_results"),
    path("api/update-duration/<int:test_id>/", update_duration, name="update_duration"),
    # Student APIs
    path("api/subjects/",                  api_subjects,       name="api_subjects"),
    path("api/tests/<int:subject_id>/",    api_tests,          name="api_tests"),
    path("api/questions/<int:test_id>/",   api_questions,      name="api_questions"),
    path("api/leaderboard/<int:test_id>/", api_leaderboard,    name="api_leaderboard"),
    path("api/practice-check/",            api_practice_check,    name="api_practice_check"),
    path("api/practice-questions/<int:test_id>/", api_practice_questions, name="api_practice_questions"),
    path("api/subject-question-bank/<int:subject_id>/", api_subject_question_bank, name="api_subject_question_bank"),
    path("api/practice-submit/", api_practice_submit, name="api_practice_submit"),
]
